config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pokemons#index'

  resources :pokemons do
    resources :bookings, only: [:new, :create]
  end

  resources :bookings, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :reviews, only: [:new, :create]
  end

  resources :reviews, only: [:destroy]


  resources :bookings do
    resources :pokemons
    resources :conversations do
      resources :messages
    end
  end

  resources :messages


  resources :users

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :pokemon
  has_many :reviews, dependent: :destroy
  has_one :conversation, dependent: :destroy
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :booking
  has_many :messages, dependent: :destroy
end

app/models/evolution.rb
class Evolution < ApplicationRecord
  belongs_to :pokemon
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
  ELEMENTS = %W(fire grass water electricity)
  LEVELS = [1, 2, 3]

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :booking
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :pokemon
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :pokemons
  has_many :bookings
  has_many :messages
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  include Pundit

  before_action :authenticate_user!
  # Pundit: white-list approach.
  after_action :verify_authorized, except: :index, unless: :devise_controller?
  after_action :verify_policy_scoped, only: :index, unless: :devise_controller?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  private
  
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  require 'active_support/all'
  skip_after_action :verify_authorized

  def index
    @bookings = Booking.all
  end

  def new
    @already_booked = []
    @pokemon = Pokemon.find(params[:pokemon_id])
    @pokemon.bookings.all.each do |booked|
      @already_booked << booked.date
    end
    @booking = Booking.new
  end

  def show
    @booking = Booking.find(params[:id])
    @pokemon = Pokemon.find(@booking.pokemon_id)
    @conversation = Conversation.find_by(booking_id: @booking.id)
    @messages = Message.where(conversation_id: @conversation.id)
    @message = Message.new(conversation_id: @conversation.id)
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to booking_path(@booking)
  end

  def create
    @pokemon = Pokemon.find(params[:booking][:pokemon_id])
    if params[:booking][:date] == ""
      @booking = Booking.new
      redirect_to new_pokemon_booking_path(@pokemon)
      return
    else
      params[:booking][:date].split(",").each do |date|
      date.to_date
      @bookings = []
      @booking = Booking.new(date: date)
      @conversation = Conversation.new
      @booking.pokemon = @pokemon
      @booking.user = current_user
      @conversation.booking = @booking
      @conversation.save
      @booking.save
      @bookings << @booking
      end
    end
    if @booking.nil?
      @booking = Booking.new
      render :new
    elsif @bookings.each(&:save)
      redirect_to user_path(@booking.user)
    else
      @booking = Booking.new
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to user_path(current_user)
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :status)
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  skip_after_action :verify_authorized

  def create 
    @message = Message.new(message_params)
    @conversation = Conversation.find(params[:message][:conversation_id])
    @message.conversation = @conversation
    @message.user_id = current_user.id
    @message.save
    redirect_to booking_path(@conversation.booking)
  end 

  private

  def message_params
    params.require(:message).permit(:content)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    if params[:query].present?
      @pokemons = policy_scope(Pokemon.where("name ILIKE ?", "%#{params[:query]}%"))
    else
      @pokemons = policy_scope(Pokemon)
    end
  end

  def new
    @pokemon = Pokemon.new
    authorize @pokemon
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    authorize @pokemon
    @pokemon.user = current_user
    if @pokemon.save
      redirect_to pokemon_path(@pokemon)
    else
      render :new
    end
  end

  def edit
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
  end

  def update
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
    @pokemon.update(pokemon_params)
    redirect_to pokemon_path(@pokemon)
  end

  def show
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
    @reviews = Review.all
  end

  def destroy
    @pokemon = Pokemon.find(params[:id])
    authorize @pokemon
    @pokemon.destroy
    redirect_to pokemons_path
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :description, :element, :evolution_level, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  skip_after_action :verify_authorized

  def new
    @booking = Booking.find(params[:booking_id])
    @review = Review.new
  end

  def create
    @booking = Booking.find(params[:booking_id])
    @review = Review.new(review_params)
    @review.booking = @booking
    if @review.save
      redirect_to booking_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to booking_path(@review.booking)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_after_action :verify_authorized

  def show
    @user = User.find(params[:id])
    @bookings = Booking.where(user_id: @user.id)
    @pokemons = Pokemon.where(user_id: @user.id)
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to user_path(@user)
  end

  private

  def user_params
    params.require(:user).permit(:email, :firstname, :lastname, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container show_booking ptpb">
  <h3>Book Your Pokemon</h3>

  <div class="calendar_show">
    <div class="calendar_container">
      <% @already_booked %>
      <%= month_calendar pokemon: @bookings do |date, bookings| %>
        <!--display date if today's date  and not booked-->
        <% if date > DateTime.current.to_date && @already_booked&.exclude?(date)%>
            <div class="cursor" style="cursor: pointer;">
              <div class="round">
              <%= date.day %>
              </div>
              <!-- content of the complete date -->
              <span style="display: none"><%= date %></span>
            </div>
        <!--past days note proposed -->
        <% else %>
        <div class="cursor-past" style="cursor: pointer;">
          <div class="round">
          <%= date.day %>
          </div>
          <span style="display: none"><%= date %></span>
        </div>
        <% end %>
      <% end %>
    </div>

<div class="card">
        <%if @pokemon.photo.attached? %>
          <%= link_to pokemon_path(@pokemon) do %>
            <%= cl_image_tag @pokemon.photo.key, class: "card-img-top" %>
          <% end %>
        <% else %>
          <div class="pokemon-product-index" style="background-image: url(<%= image_url("#{pokemon.element}.png")%>);">
            <h4 class="pokemon-name"><%= pokemon.name %></h4>
          </div>
        <% end %>
        <div class="card-body">
          <h4 class="card-title">
            <%= @pokemon.name %>
            <%= image_tag "#{@pokemon.element}.png", class: "element" %>
          </h4>
          <p>
            <%= @pokemon.description %>
          </p>
          <% if policy(@pokemon).show? %>
          <%= link_to 'See more', pokemon_path(@pokemon), :class => 'btn btn-primary' %>
          <% end %>
        </div>
      </div>


  </div>

  <div class="calendar_form">
    <%= simple_form_for @booking, wrapper: :inline_form do |f| %>
      <%= f.input :pokemon_id, :as => :hidden, :input_html => { :value => params[:pokemon_id] } %>
      <%= f.input :date, label: "Date of Booking", as: :string, as: :hidden%>
      <%= f.button :submit %>
    <% end %>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container ptpb">
  <h1>Your booking</h1>
  <br>
  <div class="card-product">
    <%if @pokemon.photo.attached? %>
      <%= cl_image_tag @pokemon.photo.key, class: "card-product-img" %>
    <% end %>
    <div class="card-product-infos">
      <ul>
        <li><h5><%=@booking.pokemon.name%></h5></li>
        <br>
        <li><h6>Renter : </h6> <%=@booking.user.email  %> </li>
        <br>
        <li><h6>Owner : </h6> <%=@pokemon.user.email  %> </li>
      </ul>
    </div>
    <div class="card-product-infos">
      <li><h6>Date: </h6> <%= @booking.date %> </li>
      <br>
      <h6>Booking status :
        <% if @booking.status == nil %>
            <p style="color:pink">Waiting for confirmation</p>
              <% unless current_user == @booking.user %>
                 <div class="d-flex">
                  <%= simple_form_for(@booking) do |f| %>
                    <%= f.input :status, as: :hidden, input_html: {value: true} %>
                    <%= f.submit "Confirm", class: "mr-3", id: "btn-booking"  %>
                  <% end %>
                  <%= simple_form_for(@booking) do |f| %>
                    <%= f.input :status, as: :hidden, input_html: {value: false} %>
                    <%= f.submit "Refuse", id: "btn-booking" %>
                  <% end %>
                </div>
               <% end %>
        <% elsif @booking.status == true %>
          <p style="color:green">Confirmed</p>
        <% else %>
          <p style="color:red">Refused</p>
        <% end %>
      </h6>
    </div>
  </div>
<br>

  <p><%= link_to 'Add a review', new_booking_review_path(@booking) %></p>

  <h2>Conversation: </h2>
  <br>

  <% @messages.each do |message| %>
    <div class="message">
      <p><strong><%= message.content %></strong></p>
      <div class="author"><%= User.find(message.user_id).email %></div>
    </div>
  <% end %>

  <div class="messageform">
    <%= simple_form_for @message do |f| %>
      <%= f.input :content, input_html: { class: 'question' }, label: 'Send a message to the owner'%>
      <%= f.input :conversation_id, :as => :hidden, :input_html => { :value => @conversation.id } %>
      <%= f.button :submit %>
  <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokerent</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css2?family=Fjalla+One&display=swap', 'https://fonts.googleapis.com/css?family=Open+Sans&subset=latin', 'https://fonts.googleapis.com/css2?family=Poppins&display=swap', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <script src="https://unpkg.com/scrollreveal"></script>
  </head>
  <body>

  <%= render 'shared/navbar' %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/pokemons/_form.html.erb
<%= simple_form_for pokemon do |f| %>
  <%= f.input :name %>
  <%= f.input :description %>
  <%= f.input :element, collection: Pokemon::ELEMENTS , prompt: "Select one" %>
  <%= f.input :evolution_level, collection: Pokemon::LEVELS , prompt: "Select one" %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Save the pokemon", class: 'btn btn-primary' %>
<% end %>

app/views/pokemons/edit.html.erb
<div class="container ptpb">
<h1>Edit the pokemon <%= @pokemon.name %></h1>
<%= render "form", pokemon: @pokemon %>
</div>

app/views/pokemons/index.html.erb
<% unless params[:query].present? %>
<div class="banner" style="background-image: url('https://i.postimg.cc/Zqj5bFvc/pokelist.png');">
    <h1 class="text-center">Find the best pokemon for you!</h1>
</div>
<div class="container">
<% else %>
<div class="container ptpb">
<% end %>


<div class="row">
    <form autocomplete="off" action="/action_page.php">
      <div class=""><input class="form-control searchbar" id="myInput" type="text" name="pokemons" placeholder="Pika" data-pokemons="<%=@pokemons.pluck(:name).to_json%>"></div>
      <div class=""><input class= "btn btn-primary searchbtn" value="SEARCH" type="submit"></div>
    </form>
</div>




<h4 class="intro">Featured pokemons</h4>

<div class="cards">

<% @pokemons.each_with_index do |pokemon, i| %>
      <div class="card style<%=i%>" data-name="<%=pokemon.name%>">
        <% if pokemon.user == current_user %>
            <% if current_user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar-card-owner" %>
            <% else %>
              <div class="my-poke">
                <%= current_user.email.chars.first.upcase %>
              </div>
            <% end %>
        <% end %>
        <%if pokemon.photo.attached? %>
          <%= link_to pokemon_path(pokemon) do %>
            <%= cl_image_tag pokemon.photo.key, class: "card-img-top" %>
          <% end %>
        <% else %>
          <div class="pokemon-product-index" style="background-image: url(<%= image_url("#{pokemon.element}.png")%>);">
            <h4 class="pokemon-name"><%= pokemon.name %></h4>
          </div>
        <% end %>
        <div class="card-body">
          <h4 class="card-title">
            <%= pokemon.name %>
            <%= image_tag "#{pokemon.element}.png", class: "element" %>
          </h4>
          <p>
            <%= pokemon.description %>
          </p>
          <% if policy(pokemon).show? %>
          <%= link_to 'See more', pokemon_path(pokemon), :class => 'btn btn-primary' %>
          <% end %>
        </div>
      </div>
<% end %>
</div>
</div>

app/views/pokemons/new.html.erb
<div class="container ptpb">
<h1>Create a new Pokemon</h1>
<%= render "form", pokemon: @pokemon %>
</div>

app/views/pokemons/show.html.erb
<div class="container ptpb">

<div class="poke">

<div class="row justify-content-between">

  <div class="pokemon-image col-xl-4">
    <%if @pokemon.photo.attached? %>
      <%= cl_image_tag @pokemon.photo.key, crop: :fill , class: "product-img" %>
    <% else %>
      <div class="pokemon-product" style="background-image: url(<%= image_url("#{@pokemon.element}.png")%>);">
        <h4 class="pokemon-name"><%= @pokemon.name %></h4>
      </div>
    <% end %>
  </div>

  <div class ="col-xl-8">
  <div class="pkm-description">
    <h4><%= @pokemon.name %> <%= image_tag "#{@pokemon.element}.png", class: "element" %></h4>
     <p> <%= @pokemon.description %><br><br> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
    <h5>Evolution level:  <%= @pokemon.evolution_level %></h5>
  </div>
  <div class="pkm-trainer">

        <% if @pokemon.user.photo.attached? %>
        <%= cl_image_tag @pokemon.user.photo.key, class: "avatar", 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= image_tag "https://i.skyrock.net/6160/62596160/pics/2519591537_1.jpg", class: "avatar", 'aria-expanded': false %>
        <% end %>
        <p> <strong>Trainer:</strong> <%= @pokemon.user.email %><p>


        <% if policy(@pokemon).update? %>
          <%= link_to 'Update infos', edit_pokemon_path(@pokemon), :class => 'btn btn-primary btn-edit' %>
        <% end %>
        <% if policy(@pokemon).destroy? %>
          <%= link_to "Delete", pokemon_path(@pokemon), method: :delete, :class => 'btn btn-primary btn-delete' %>
        <% end %>
  </div>
</div>

</div>
<% if @pokemon.user != current_user %>
  <%= link_to 'Book me', new_pokemon_booking_path(@pokemon), :class => 'btn btn-book btn-primary' %>
<% end %>


<h4 class="text-center">Reviews</h4>
<br>
  <% @reviews.each do |review| %>
    <% if review.booking.pokemon == @pokemon %>
      <div class="review">
        <p><strong><%= review.content %></strong>
        <div class="useremail">
        <% if review.booking.user.photo.attached? %>
        <%= cl_image_tag review.booking.user.photo.key, class: "avatar", 'aria-haspopup': true, 'aria-expanded': false %>
        <% else %>
        <%= image_tag "https://i.skyrock.net/6160/62596160/pics/2519591537_1.jpg", class: "avatar", 'aria-expanded': false %>
        <% end %>
        <%= review.booking.user.email %></div>
        <% link_to 'Delete', review_path(review), method: :delete, data: {confirm: "Are you sure?"}%>
        </p>
      </div>
    <% end %>
  <% end %>

</div>

app/views/reviews/new.html.erb
<div class="container ptpb">

<%= simple_form_for [@booking, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

</div>

app/views/shared/_footer.html.erb
<div class="footer fixed-bottom">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    We are the best pokemon team <i class="fas fa-heart"></i> Don't fuck with us
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top">
  <%= link_to "/", class: "navbar-brand" do %>
    <%= image_tag "pika.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <%= link_to "Pokemons", pokemons_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <% if policy(Pokemon).create? %>
          <%= link_to "Add a pokemon", new_pokemon_path, class: "nav-link" %>
        <% end%>
        </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown">
          <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% else %>
            <%= image_tag "https://i.skyrock.net/6160/62596160/pics/2519591537_1.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Dashboard", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container ptpb">
  <h1>Edit my profile</h1>
  <%= simple_form_for @user do |f| %>
    <%= f.input :firstname, :label => "First Name" %>
    <%= f.input :lastname, :label => "Last Name" %>
    <%= f.input :email, :label => "Email" %>
    <%#= f.input :current_password %>
    <%#= f.input :password %>
    <%#= f.input :password_confirmation %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Save", class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container ptpb">
  <div class="cards">
    <div class="card dash" style="width: 48%">
      <h1>MY BOOKINGS</h1>
        <div class="card-container">
        <% @bookings.each do |booking| %>
          <div class="card-product-booking">
            <%= link_to booking_path(booking) do %>
              <% if booking.pokemon.photo.attached? %>
                <%= cl_image_tag booking.pokemon.photo.key, id:"card-product-booking-img" %>
              <% else %>
                <!-- <div class="pokemon-element" style="background-image: linear-gradient(90deg, rgba(255,255,255,0.5) 100%, rgba(247,247,247,0.5) 100%, rgba(255,255,255,1) 100%),url(<%= image_url("#{pokemon.element}.png")%>);">
                  <h4 class="pokemon-name"><%= booking.pokemon.name %></h4>
                </div> -->
              <% end %>
            <% end %>
            <div class="card-product-booking-infos">
              <h6>Date</h6>
              <p><%=booking.date %></p>
            </div>
            <div class="card-product-booking-infos">
              <h6>Status</h6>
                <% if booking.status == nil %>
                  <p style="color:pink">To confirm</p>
                <% elsif booking.status == true %>
                  <p style="color:green">Confirmed</p>
                <% else %>
                  <p style="color:red">Refused</p>
                <% end %>
            </div>
            <div class="card-product-booking-infos">
                <p><%= link_to booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' } do %>
                  <i class="far fa-trash-alt"></i>
                <% end %></p>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="card dash" style="width: 48%">
      <h1>MY POKEMONS</h1>
        <div class="card-container">
        <% @pokemons.each do |pokemon| %>
          <div class="card-product-booking">
              <% if pokemon.bookings.empty? %>
                <%= link_to pokemon_path(pokemon) do %>
                  <%= cl_image_tag pokemon.photo.key, id:"card-product-booking-img" %>
                <% end %>
                <div class="card-product-booking-infos">
                <p>Not booked yet</p>
                </div>

              <% else %>
                <%= link_to booking_path(pokemon.bookings.first) do %>
                  <% if pokemon.photo.attached?%>
                    <%= cl_image_tag pokemon.photo.key, id:"card-product-booking-img" %>
                  <% else %>
                    <!-- <div class="pokemon-element card-product-img" style="background-image: linear-gradient(90deg, rgba(255,255,255,0.5) 100%, rgba(247,247,247,0.5) 100%, rgba(255,255,255,1) 100%),url(<%= image_url("#{pokemon.element}.png")%>);">
                      <h4 class="pokemon-name"><%= pokemon.name %></h4>
                    </div> -->
                  <% end %>
                  <% end %>
              <% end %>
              <% if pokemon.bookings %>
                <% pokemon.bookings.each do |booking| %>
                  <div class="card-product-booking-infos">
                   <h6>Date</h6>
                    <p><%= booking.date %> </p>
                  </div>
                  <div class="card-product-booking-infos">
                    <h6>Status</h6>
                    <% if booking.status == nil %>
                      <p style="color:pink">To confirm</p>
                    <% elsif booking.status == true %>
                      <p style="color:green">Confirmed</p>
                    <% elsif booking.status == false %>
                      <p style="color:red">Refused</p>
                    <% end %>
                  </div>
                  <div class="card-product-booking-infos">
                    <p><%= link_to booking_path(booking), method: :delete, data: { confirm: 'Are you sure?' } do %>
                      <i class="far fa-trash-alt"></i>
                      <% end %></p>
                  </div>
                  <% end %>
              <% end %>
          </div>
        <% end %>
      </div>
    </div>

      <div class="card" style="width: 97.5%">
        <h1>MY ACCOUNT</h1>
        <% if @user.photo.attached? %>
          <%= cl_image_tag @user.photo.key, class: "avatar-my-account" %>
        <% else %>
          <p><%= link_to 'Choose a profile picture', edit_user_path(@user) %></p>
        <% end %>
        <br>
        <p><strong>First Name:</strong> <%= @user.firstname %></p>
        <p><strong>Last Name:</strong> <%= @user.lastname %></p>
        <p><strong>My email:</strong> <%= @user.email %></p>
        <br>
        <p><strong><%= link_to 'Edit my profile', edit_user_path(@user) %></strong></p>
      </div>
    </div>
  </div>